# Generated by Django 5.0.6 on 2024-06-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaAcademico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='idAlumno',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='idCurso',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notasalumnoporcurso',
            name='idNotasAlumnoPorCurso',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notasalumnoporcurso',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
